### ISSUE TITLE
Separating dpad and left joystick

### ISSUE THREAD

**Issue by pickledgator** [aevzp/flutter-gamepad#1]
First of all, THANKS for putting this together!

I've been giving your library a whirl on an S192K gamepad tablet. It's working quite well! I've been playing around with try to separate out the dpad button presses from the left joystick commands, despite that they show up from the same sources within the Android events. I was able to modify the `isDpadDevice` method to single out the leading edges nicely:

```
public static boolean isDpadDevice(InputEvent event) {
        // Check that input comes from a device with directional pads.
        MotionEvent motionEvent = (MotionEvent) event;
        float xaxis = motionEvent.getAxisValue(MotionEvent.AXIS_HAT_X);
        float yaxis = motionEvent.getAxisValue(MotionEvent.AXIS_HAT_Y);
        boolean maxHatValue = Math.abs(xaxis) == 1.0 || Math.abs(yaxis) == 1.0;
        if ((Math.abs(motionEvent.getX(0) - 0.0f) < 0.01) && (Math.abs(motionEvent.getY(0) - 0.0f) < 0.01) && maxHatValue) {
          return true;
        } else {
          return false;
        }
    }
```

Then change the switch statement in the `onGenericMotionEvent` to remove extra Axis callbacks for dpad presses:
```
else if ((event.getSource() & InputDevice.SOURCE_JOYSTICK) ==
                InputDevice.SOURCE_JOYSTICK &&
                event.getAction() == MotionEvent.ACTION_MOVE) {
```

However, this still results in Axis calls when the dpad buttons are released since the `isDpadDevice` logic is too primitive. See output below. Do you have any thoughts? 
```
I/flutter (14105): Dpad: type: DPAD, direction: 2 <-- pressed
I/flutter (14105): Axis: type: AXIS, sourceInput: STICK_LEFT, x: 0.003921628, y: 0.003921628 <-- released
I/flutter (14105): Axis: type: AXIS, sourceInput: STICK_RIGHT, x: 0.003921628, y: 0.003921628
I/flutter (14105): Dpad: type: DPAD, direction: 3 <-- pressed 
I/flutter (14105): Axis: type: AXIS, sourceInput: STICK_LEFT, x: 0.003921628, y: 0.003921628 <-- released
I/flutter (14105): Axis: type: AXIS, sourceInput: STICK_RIGHT, x: 0.003921628, y: 0.003921628
I/flutter (14105): Dpad: type: DPAD, direction: 3
I/flutter (14105): Axis: type: AXIS, sourceInput: STICK_LEFT, x: 0.003921628, y: 0.003921628
I/flutter (14105): Axis: type: AXIS, sourceInput: STICK_RIGHT, x: 0.003921628, y: 0.003921628
```

Also, seemingly seeing some instabilities with dpad button presses (but not any of the other buttons):
```
I/flutter (14105): Dpad: type: DPAD, direction: 2
I/flutter (14105): Dpad: type: DPAD, direction: 2
I/flutter (14105): Dpad: type: DPAD, direction: 2
I/flutter (14105): Dpad: type: DPAD, direction: 0
I/flutter (14105): Dpad: type: DPAD, direction: 1
I/flutter (14105): Dpad: type: DPAD, direction: 3
E/MethodChannel#flutter/platform_views(14105): Failed to handle method call
E/MethodChannel#flutter/platform_views(14105): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View io.flutter.plugin.platform.VirtualDisplayController.getView()' on a null object reference
E/MethodChannel#flutter/platform_views(14105): 	at io.flutter.plugin.platform.PlatformViewsController$1.clearFocus(PlatformViewsController.java:341)
E/MethodChannel#flutter/platform_views(14105): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.clearFocus(PlatformViewsChannel.java:196)
E/MethodChannel#flutter/platform_views(14105): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:74)
E/MethodChannel#flutter/platform_views(14105): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/platform_views(14105): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/platform_views(14105): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#flutter/platform_views(14105): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(14105): 	at android.os.MessageQueue.next(MessageQueue.java:143)
E/MethodChannel#flutter/platform_views(14105): 	at android.os.Looper.loop(Looper.java:122)
E/MethodChannel#flutter/platform_views(14105): 	at android.app.ActivityThread.main(ActivityThread.java:5284)
E/MethodChannel#flutter/platform_views(14105): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(14105): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/MethodChannel#flutter/platform_views(14105): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
E/MethodChannel#flutter/platform_views(14105): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
I/flutter (14105): Dpad: type: DPAD, direction: 2
E/flutter (14105): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.view.View io.flutter.plugin.platform.VirtualDisplayController.getView()' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View io.flutter.plugin.platform.VirtualDisplayController.getView()' on a null object reference
E/flutter (14105): 	at io.flutter.plugin.platform.PlatformViewsController$1.clearFocus(PlatformViewsController.java:341)
E/flutter (14105): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.clearFocus(PlatformViewsChannel.java:196)
E/flutter (14105): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:74)
E/flutter (14105): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (14105): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (14105): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/flutter (14105): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (14105): 	at android.os.MessageQueue.next(MessageQueue.java:143)
E/flutter (14105): 	at android.os.Looper.loop(Looper.java:122)
E/flutter (14105): 	at android.app.ActivityThread.main(ActivityThread.java:5284)
E/flutter (14105): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (14105): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/flutter (14105): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
E/flutter (14105): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
E/flutter (14105): )
E/flutter (14105): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
E/flutter (14105): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
E/flutter (14105): <asynchronous suspension>
E/flutter (14105):
```

**Comment by pickledgator** [comment]
Ok so turns out you just have to look at `AXIS_HAT_X` to separate out the dpad events from joystick events, which show up as `AXIS_X` events. I updated my `isDPadEvent` method to look like this and it works nicely:

```
public boolean isDPadEvent(InputEvent event) {
        // Check that input comes from a device with directional pads.
        MotionEvent motionEvent = (MotionEvent) event;
        float xHat = motionEvent.getAxisValue(MotionEvent.AXIS_HAT_X);
        float yHat = motionEvent.getAxisValue(MotionEvent.AXIS_HAT_Y);
        // New event is a button press
        if(state == CENTER && (xHat != 0.0f || yHat != 0.0f)) {
          return true;
        }
        // New event is a button release
        else if( state != CENTER && (xHat == 0.0f || yHat == 0.0f)) {
          return true;
        }
        // Not a dpad event
        return false;
    }
```

I do still get random `NullPointerException`'s though if you have any thoughts on that one.

**Comment by pickledgator** [comment]
For those keeping score at home, the issue with the nullpointer was related to accidentally passing dpad events back upstream through the `return super.onGenericMotionEvent(event);`. It was defocusing the listener. I'll push my changes to my own repo here shortly incase you or anyone else is interested in my changes / cleanups.

**Comment by gedw99** [comment]
I would be interested 

am try to get dpad support for desktop, Apple TV and Google tv happening and it’s good to see the code to gain insight. Hope you don’t mind

**Comment by aevzp** [comment]
Hi to all.

Sorry, but now I don't have free time for continue developing this package for all needs.
Hybrid composition does not have a very good impact on application performance, especially if you want to transfer something similar to `Texture` and use a gamepad at the same time, so you'll have problem with weak TV boxes.

If anyone finds a better gamepad solution please let me know.
